export const TASKS_DATA = {
  title: "tasks",
  items: [
    {
      id: 1,
      title: "Task title 1",
      description: "Task description about task",
      project: "inbox",
      date: "12.23.2322",
      priority: "HIGH",
      labels: ["tasks", "todo", "plans"],
    },
    {
      id: 2,
      title: "Task title 2",
      description: "Task description about task",
      project: "inbox",
      date: "12.23.2322",
      priority: "HIGH",
      labels: ["tasks", "todo", "plans"],
    },
    {
      id: 3,
      title: "Task title 3",
      description: "Task description about task",
      project: "inbox",
      date: "12.23.2322",
      priority: "HIGH",
      labels: ["tasks", "todo", "plans"],
    },
    {
      id: 4,
      title: "Task title 4",
      description: "Task description about task",
      project: "inbox",
      date: "12.23.2322",
      priority: "HIGH",
      labels: ["tasks", "todo", "plans"],
    },
    {
      id: 5,
      title: "Task title 5",
      description: "Task description about task",
      project: "inbox",
      date: "12.23.2322",
      priority: "HIGH",
      labels: ["tasks", "todo", "plans"],
    },
  ],
};
