import { guid } from "./context/idGenerator";

export const TASKS_DATA = {
  title: "tasks",
  items: [
    {
      id: guid(),
      title: "Task title 1",
      description: "Task description about task",
      project: "inbox",
      date: "12.23.2322",
      priority: "HIGH",
      labels: ["tasks", "todo", "plans"],
      isDone: false,
    },
    {
      id: guid(),
      title: "Task title 2",
      description: "Task description about task",
      project: "work",
      date: "12.23.2322",
      priority: "MEDIUM",
      labels: ["tasks", "todo", "plans"],
      isDone: false,
    },
    {
      id: guid(),
      title: "Task title 3",
      description: "Task description about task",
      project: "inbox",
      date: "12.23.2322",
      priority: "HIGH",
      labels: ["tasks", "todo", "plans"],
      isDone: false,
    },
    {
      id: guid(),
      title: "Task title 4",
      description: "Task description about task",
      project: "home",
      date: "12.23.2322",
      priority: "LOW",
      labels: ["tasks", "todo", "plans"],
      isDone: false,
    },
    {
      id: guid(),
      title: "Task title 5",
      description: "Task description about task",
      project: "inbox",
      date: "12.23.2322",
      priority: "HIGH",
      labels: ["tasks", "todo", "plans"],
      isDone: false,
    },
  ],
};
